### ISSUE TITLE
Build issue with MQ dependency jar

### ISSUE THREAD

**Issue by callmeberzerker** [cpiotr/blog#1]
Hello,

Curious if your solution still builds, because I can not get ahold of MQ jars namely the com.ibm:com.ibm.mqjms:5.3.07 

It seems the for download the jar is returning 404.

**Comment by cpiotr** [comment]
That's because all the MQ jars are not present in any public repository. 
You have to either add them manually to your repo or change scope.
I've switched the scope in my project to system: https://github.com/cpiotr/blog/commit/bceb98af343dabddfac0a5c411c358f00a7c5dff. 

Thanks for your remark!
