### ISSUE TITLE
dependancy cant be resolved

### ISSUE THREAD

**Issue by anandvarkeyphilips** [cpiotr/blog#3]
import com.ibm.msg.client.wmq.WMQConstants; cannot be found.
Please add the pom file.
@data @inject is also not resolvable.

**Comment by cpiotr** [comment]
Hi,
take a look at https://github.com/cpiotr/blog/blob/master/blog-code/pom.xml 
In order to resolve IBM MQ libraries, you need to have them installed on your machine. They're proprietary software. 

@Data comes from lombok
@Inject comes from javax.inject which indirectly comes from Google Guice.
