### ISSUE TITLE
connectionFactory bean can not be instantiated

### ISSUE THREAD

**Issue by hormelspammer** [cpiotr/blog#4]
Piotr,

I read your page "Connecting to IBM MQ with Spring Boot and JMS" and liked how it was configured and so I implemented mine the same way.  But I'm getting a error that the connectionFactory bean can not be instantiated.  When doing 'factory = new MQConnectionFactory()', it keeps coming back as null.

Any ideas as to what I'm missing?

Thanks in advance!

**Comment by cpiotr** [comment]
@hormelspammer: If calling a constructor `factory = new MQConnectionFactory()` comes back as `null`, it seems that there's an exception thrown somewhere, which is probably ignored. 
Are you sure you have MQ jars on your classpath?
Have you tried debugging your code?

**Comment by hormelspammer** [comment]
@cpiotr: I forgot to update this once I figured out what was going on.  I had included some of the MQ jars to resolve the 'classdefnotfound' errors but was still getting the null.  Once I included all the MQ jars, it worked fine.  So apparently it referenced something in the other jars but didn't throw a 'classdefnotfound' error or it was ignored like you mentioned.

Thanks for your response!
